// FE_angular/src/app/components/product-card/product-card.component.ts
import { Component, Input, inject } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { CartService } from '../../services/cart.service';
import { DragDropCartService } from '../../services/drag-drop-cart.service';

@Component({
  selector: 'app-product-card',
  standalone: true,
  imports: [CommonModule, RouterModule, CurrencyPipe],
  template: `
    <div [draggable]="true"
         (dragstart)="onDragStart($event)"
         (dragend)="onDragEnd($event)"
         (mouseenter)="onMouseEnter()"
         (mouseleave)="onMouseLeave()"
         class="group block relative cursor-grab active:cursor-grabbing outline-none select-none bg-white rounded-2xl p-2 border border-gray-100 hover:border-amber-400/40 hover:shadow-lg transition-all duration-300">
      
      <!-- Image Container with Hover Overlay -->
      <div class="relative bg-gray-50 overflow-hidden rounded-xl aspect-[3/4] mb-2.5">
        
        <!-- Main Image -->
        <img *ngIf="product?.main_img" 
             [src]="product.main_img" 
             [alt]="product.name" 
             class="w-full h-full object-cover transition-transform duration-700 ease-out group-hover:scale-105">
        
        <!-- Hover Secondary Image -->
        <img *ngIf="product?.images?.length && product?.images?.[0] !== product?.main_img" 
             [src]="product.images[0]" 
             [alt]="product.name + ' hover'" 
             class="absolute inset-0 w-full h-full object-cover opacity-0 transition-opacity duration-500 ease-out group-hover:opacity-100 group-hover:scale-105">

        <!-- Fallback Placeholder -->
        <div *ngIf="!product?.main_img && !product?.images?.length" class="w-full h-full flex flex-col items-center justify-center text-gray-300">
          <i class="fa-solid fa-shirt text-3xl mb-2"></i>
          <span class="text-[10px] font-bold uppercase tracking-widest">No Image</span>
        </div>

        <!-- Top Badges (CLOSET Brand Tag & Discount Badge) -->
        <div class="absolute top-2 left-2 z-10 flex flex-col gap-1 items-start">
          <span class="px-2 py-0.5 bg-black/80 backdrop-blur-md text-amber-400 text-[8px] font-serif-brand font-black uppercase tracking-[0.2em] rounded-md shadow-sm border border-amber-400/30">
            CLOSET
          </span>
          <span *ngIf="product?.discount_percent > 0" 
                class="px-2 py-0.5 bg-red-600 text-white text-[9px] font-black uppercase tracking-wider rounded-md shadow-md animate-pulse">
            -{{ product.discount_percent }}%
          </span>
        </div>

        <!-- Glassmorphism Hover Overlay Actions -->
        <div class="absolute inset-0 bg-black/50 backdrop-blur-[2px] opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col items-center justify-center gap-2 p-3 z-20">
          
          <!-- Xem chi tiết -->
          <button (click)="viewDetail($event)" 
                  class="w-full py-2 bg-white/90 hover:bg-white text-gray-900 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all shadow-md active:scale-95 flex items-center justify-center gap-1.5">
            <i class="fa-regular fa-eye"></i> Xem chi tiết
          </button>

          <!-- Mua ngay -->
          <button (click)="quickBuy($event)" 
                  class="w-full py-2 bg-brand-black hover:bg-black text-brand-gold rounded-xl text-[10px] font-black uppercase tracking-wider transition-all shadow-md active:scale-95 flex items-center justify-center gap-1.5 border border-brand-gold/60">
            <i class="fa-solid fa-bag-shopping"></i> Mua ngay
          </button>

          <!-- Drag Badge Tip -->
          <span class="text-[8px] font-extrabold uppercase tracking-widest text-amber-300 mt-1 flex items-center gap-1">
            <i class="fa-solid fa-hand-pointer animate-bounce"></i> Kéo thả giỏ hàng
          </span>
        </div>
      </div>
      
      <!-- Details -->
      <div class="px-1 text-center" (click)="viewDetail($event)">
        <!-- Category / Brand Line -->
        <span class="block text-[9px] font-extrabold uppercase tracking-[0.2em] text-amber-600 mb-0.5 line-clamp-1">
          {{ product?.category_id?.name || product?.brand_id?.name || 'LUXURY SELECTION' }}
        </span>

        <!-- Product Name -->
        <h3 class="text-[12px] font-extrabold text-gray-900 uppercase tracking-wide leading-tight line-clamp-1 group-hover:text-amber-600 transition-colors">
          {{ product?.name }}
        </h3>

        <!-- Price & Discount -->
        <div class="flex items-center justify-center gap-1.5 mt-1.5">
          <span class="text-xs font-black text-gray-900">
            {{ (product?.sale_price || product?.price || product?.default_price || (product?.variants?.[0]?.price) || 350000) | currency:'VND':'symbol':'1.0-0' }}
          </span>
          <span *ngIf="product?.original_price && product?.original_price > (product?.sale_price || product?.price || product?.default_price || 0)" 
                class="text-[9px] text-gray-400 line-through">
            {{ product.original_price | currency:'VND':'symbol':'1.0-0' }}
          </span>
        </div>
      </div>
    </div>
  `
})
export class ProductCardComponent {
  @Input() product: any;

  private cartService = inject(CartService);
  private dragDropService = inject(DragDropCartService);
  private router = inject(Router);

  onMouseEnter() {
    this.dragDropService.showDropZone();
  }

  onMouseLeave() {
    this.dragDropService.hideDropZone();
  }

  onDragStart(event: DragEvent) {
    this.dragDropService.showDropZone();
    if (event.dataTransfer && this.product) {
      event.dataTransfer.setData('application/json', JSON.stringify(this.product));
      event.dataTransfer.effectAllowed = 'copy';
    }
  }

  onDragEnd(event: DragEvent) {
    this.dragDropService.hideDropZone();
  }

  viewDetail(event: Event) {
    event.stopPropagation();
    this.dragDropService.hideDropZone();
    const id = this.product?.slug || this.product?._id || this.product?.id;
    if (id) {
      this.router.navigate(['/product', id]);
    }
  }

  quickBuy(event: Event) {
    event.stopPropagation();
    this.dragDropService.hideDropZone();
    if (!this.product) return;
    
    const buyItem = {
      id: `${this.product._id || this.product.id}`,
      product_id: this.product._id || this.product.id,
      variant_id: this.product.variants?.[0]?._id || this.product._id || this.product.id,
      name: this.product.name,
      price: this.product.sale_price || this.product.price || this.product.default_price || (this.product.variants?.[0]?.price) || 350000,
      quantity: 1,
      image: this.product.main_img || 'https://via.placeholder.com/150'
    };

    this.cartService.setBuyNowItem(buyItem);
    this.router.navigate(['/checkout']);
  }
}

// fe-react/src/components/client/ProductCard/index.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Product } from "../../../types";
import { useCart } from "../../../context/CartContext";

export interface ProductCardProps {
  product: Product;
}

export default function ProductCard({ product }: ProductCardProps) {
  const [addedToast, setAddedToast] = useState(false);

  const price =
    product.default_price ||
    (product.variants && product.variants.length > 0
      ? product.variants[0].price
      : 0);

  const colors = product.variants
    ? Array.from(new Map(product.variants.map((v) => [v.color_hex, v])).values())
    : [];

  const cart = useCart();

  const handleAddToCart = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    
    cart.addToCart({
      product_variant_id: (product.variants?.[0] as any)?._id || null,
      product_id: product._id,
      name: product.name,
      price: price,
      quantity: 1,
      image: product.main_img || '',
      size: product.variants?.[0]?.size,
      color: product.variants?.[0]?.color,
    });
    
    setAddedToast(true);
    setTimeout(() => setAddedToast(false), 2500);
  };

  return (
    <div className="product-card group flex flex-col relative">
      {/* Toast Notification */}
      {addedToast && (
        <div className="absolute top-2 left-2 right-2 z-30 bg-emerald-600 text-white text-[10px] font-black px-3 py-2 rounded-xl shadow-2xl flex items-center justify-center gap-1.5 animate-bounce">
          <i className="fa-solid fa-circle-check text-xs" />
          <span>Đã thêm vào giỏ!</span>
        </div>
      )}

      {/* Image Frame */}
      <div className="relative overflow-hidden aspect-[3/4] bg-slate-100 dark:bg-slate-800/80 rounded-2xl mb-3 border border-slate-200/50 dark:border-slate-800 shadow-sm">
        {product.main_img ? (
          <Image
            src={product.main_img}
            alt={product.name}
            fill
            sizes="(max-width: 768px) 100vw, 300px"
            unoptimized
            className="card-img object-cover transition-transform duration-500 group-hover:scale-105"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center bg-slate-200 dark:bg-slate-800 text-slate-400 font-bold text-xs">
            CLOSET.
          </div>
        )}

        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 dark:group-hover:bg-black/40 transition-all duration-500" />

        {/* Hover Action Buttons (Chi tiết & Thêm giỏ hàng) */}
        <div className="card-overlay absolute bottom-3 left-3 right-3 opacity-0 group-hover:opacity-100 transform translate-y-3 group-hover:translate-y-0 transition-all duration-300 flex items-center gap-2 z-20">
          <Link
            href={`/product/${product._id}`}
            className="flex-1 py-2 bg-white/95 dark:bg-slate-900/95 backdrop-blur-md text-slate-900 dark:text-white text-[9px] font-black uppercase tracking-wider text-center rounded-xl shadow-lg hover:bg-slate-950 hover:text-white dark:hover:bg-[#D4AF37] dark:hover:text-slate-950 transition-all flex items-center justify-center gap-1.5"
          >
            <i className="fa-solid fa-eye text-[10px]" />
            <span>Chi tiết</span>
          </Link>

          <button
            type="button"
            onClick={handleAddToCart}
            className="flex-1 py-2 bg-indigo-600 dark:bg-[#D4AF37] text-white dark:text-slate-950 text-[9px] font-black uppercase tracking-wider text-center rounded-xl shadow-lg hover:bg-indigo-700 dark:hover:bg-[#EBC563] transition-all flex items-center justify-center gap-1.5"
            title="Thêm vào giỏ hàng"
          >
            <i className="fa-solid fa-bag-shopping text-[10px]" />
            <span>+ Thêm giỏ</span>
          </button>
        </div>
      </div>

      {/* Color Swatches */}
      {colors.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mb-2.5 px-1">
          {colors.slice(0, 4).map((c, idx) => (
            <span
              key={idx}
              className="w-3.5 h-3.5 rounded-full border border-slate-300 dark:border-slate-700 shadow-inner"
              style={{ backgroundColor: c.color_hex }}
              title={c.color}
            />
          ))}
          {colors.length > 4 && (
            <span className="text-[10px] text-slate-500 dark:text-slate-400 font-bold ml-0.5">
              +{colors.length - 4}
            </span>
          )}
        </div>
      )}

      {/* Details */}
      <div className="flex justify-between items-start px-1 mt-auto">
        <div className="flex-1 min-w-0 mr-3">
          <h3 className="text-[11px] font-black uppercase tracking-widest text-slate-900 dark:text-slate-100 mb-1 leading-tight hover:text-indigo-600 dark:hover:text-[#EBC563] transition-colors line-clamp-2">
            <Link href={`/product/${product._id}`}>{product.name}</Link>
          </h3>
          {product.category && product.category.length > 0 && (
            <p className="text-[9px] text-slate-400 dark:text-slate-500 font-bold uppercase tracking-widest">
              {product.category[0].name}
            </p>
          )}
        </div>
        <div className="text-right shrink-0">
          <p className="text-[11px] font-black text-indigo-600 dark:text-[#EBC563]">
            {price.toLocaleString("vi-VN")}đ
          </p>
        </div>
      </div>
    </div>
  );
}
