// fe-react/src/app/(client)/cart/page.tsx
'use client';

import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useCart } from '../../../context/CartContext';
import OrderSummary from '../../../components/client/OrderSummary';

export default function CartPage() {
  const router = useRouter();
  const cart = useCart();
  const { items, removeFromCart, updateQuantity, getCartTotal, getItemCount } = cart;

  const formatPrice = (p: number) => p.toLocaleString('vi-VN') + 'đ';

  if (items.length === 0) {
    return (
      <main className="pt-28 pb-20 bg-slate-50 dark:bg-[#0B0B0B] min-h-screen transition-colors duration-300">
        <div className="container mx-auto px-4 md:px-8 max-w-7xl">
          <h1 className="font-serif text-4xl md:text-5xl font-black italic mb-10 text-slate-900 dark:text-white">Giỏ hàng của bạn.</h1>
          <div className="bg-white dark:bg-[#171717] border border-transparent dark:border-slate-800 rounded-2xl p-16 text-center shadow-sm">
            <div className="w-24 h-24 bg-slate-100 dark:bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-6">
              <i className="fa-solid fa-bag-shopping text-4xl text-slate-300 dark:text-slate-600"></i>
            </div>
            <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-2">Giỏ hàng trống</h3>
            <p className="text-slate-500 dark:text-slate-400 mb-6">Bạn chưa thêm sản phẩm nào vào giỏ hàng.</p>
            <Link href="/shop" className="inline-flex items-center gap-2 px-8 py-3 bg-slate-900 dark:bg-[#D4AF37] text-white dark:text-slate-950 text-sm font-black uppercase tracking-widest rounded-full hover:bg-indigo-600 dark:hover:bg-[#EBC563] transition-all">
              <i className="fa-solid fa-bag-shopping text-xs"></i> Khám phá ngay
            </Link>
          </div>
        </div>
      </main>
    );
  }

  return (
    <main className="pt-28 pb-20 bg-slate-50 dark:bg-[#0B0B0B] min-h-screen transition-colors duration-300">
      <div className="container mx-auto px-4 md:px-8 max-w-7xl">
        <h1 className="font-serif text-4xl md:text-5xl font-black italic mb-10 text-slate-900 dark:text-white">Giỏ hàng của bạn.</h1>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 xl:gap-12 items-start">
          {/* LEFT: Cart Items */}
          <div className="lg:col-span-7 space-y-6">
            {/* Loyalty Banner */}
            <div className="bg-indigo-50 dark:bg-indigo-950/40 border border-indigo-100 dark:border-indigo-900/50 rounded-2xl px-5 py-4 flex items-center gap-4">
              <div className="w-10 h-10 bg-indigo-600 dark:bg-indigo-500 rounded-xl flex items-center justify-center flex-shrink-0">
                <i className="fa-solid fa-crown text-white text-sm"></i>
              </div>
              <div className="flex-1">
                <p className="text-sm font-bold text-slate-800 dark:text-slate-200">
                  Nhận ngay <span className="text-indigo-600 dark:text-indigo-400">Voucher -15%</span> khi tham gia CLOSET Club
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Hoàn tiền trên mọi đơn hàng và nhiều ưu đãi độc quyền.</p>
              </div>
              <button className="text-[10px] font-black uppercase tracking-widest bg-indigo-600 dark:bg-indigo-500 text-white px-5 py-2 rounded-full hover:bg-indigo-700 dark:hover:bg-indigo-600 transition-all flex-shrink-0">
                Tham gia
              </button>
            </div>

            {/* Cart Items List */}
            <div className="bg-white dark:bg-[#171717] border border-transparent dark:border-slate-800 rounded-2xl p-6 md:p-8 space-y-6 shadow-sm">
              <div className="flex items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800/60">
                <h2 className="font-serif text-xl font-black italic text-slate-900 dark:text-white">Sản phẩm ({getItemCount()})</h2>
                <button onClick={() => cart.clearCart()} className="text-[10px] font-black uppercase tracking-widest text-red-500 dark:text-red-400 hover:text-red-700 dark:hover:text-red-300 transition-all">
                  <i className="fa-solid fa-trash-can mr-1"></i> Xóa tất cả
                </button>
              </div>

              {items.map((item, idx) => (
                <div key={`${item.product_variant_id}-${item.size}-${item.color}-${idx}`} className="flex gap-5 pb-5 border-b border-slate-50 dark:border-slate-800/60 last:border-0 last:pb-0">
                  {/* Image */}
                  <div className="relative w-24 h-28 rounded-xl overflow-hidden bg-slate-100 dark:bg-slate-800 flex-shrink-0 border border-slate-200 dark:border-slate-700">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={item.image || 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=200'}
                      alt={item.name}
                      className="w-full h-full object-cover"
                    />
                  </div>

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-black uppercase tracking-wide text-slate-900 dark:text-white line-clamp-1">{item.name}</p>
                    <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5 font-medium">
                      {item.size && `Size: ${item.size}`}{item.color && ` | ${item.color}`}
                    </p>
                    <p className="text-sm font-black text-indigo-600 dark:text-[#EBC563] mt-2">{formatPrice(item.price)}</p>

                    {/* Quantity Controls */}
                    <div className="flex items-center gap-3 mt-3">
                      <div className="flex items-center border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden bg-white dark:bg-slate-800">
                        <button
                          onClick={() => updateQuantity(item.product_variant_id, item.quantity - 1, item.size, item.color)}
                          className="w-8 h-8 flex items-center justify-center text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-all text-xs"
                        >
                          <i className="fa-solid fa-minus text-[10px]"></i>
                        </button>
                        <span className="w-10 h-8 flex items-center justify-center text-xs font-black text-slate-900 dark:text-white border-x border-slate-200 dark:border-slate-700">
                          {item.quantity}
                        </span>
                        <button
                          onClick={() => updateQuantity(item.product_variant_id, item.quantity + 1, item.size, item.color)}
                          className="w-8 h-8 flex items-center justify-center text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-all text-xs"
                        >
                          <i className="fa-solid fa-plus text-[10px]"></i>
                        </button>
                      </div>
                      <button
                         onClick={() => removeFromCart(item.product_variant_id, item.size, item.color)}
                        className="text-xs text-slate-400 dark:text-slate-500 hover:text-red-500 dark:hover:text-red-400 transition-colors"
                      >
                        <i className="fa-solid fa-trash-can"></i>
                      </button>
                    </div>
                  </div>

                  {/* Line total */}
                  <div className="flex-shrink-0 text-right">
                    <p className="text-sm font-black text-slate-900 dark:text-[#EBC563]">{formatPrice(item.price * item.quantity)}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* RIGHT: Order Summary */}
          <div className="lg:col-span-5">
            <div className="sticky top-24 space-y-5">
              <OrderSummary
                itemCount={getItemCount()}
                subtotal={formatPrice(getCartTotal())}
                total={formatPrice(getCartTotal())}
                buttonText="Tiến hành thanh toán"
                onCheckout={() => router.push('/checkout')}
              />
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}

// FE_angular/src/app/pages/cart/cart.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { RouterModule } from '@angular/router';
import { CartService, CartItem } from '../../services/cart.service';

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [CommonModule, RouterModule, CurrencyPipe],
  template: `
    <div class="bg-white min-h-screen pb-[200px]">
      <!-- Header -->
      <div class="p-4 border-b border-gray-100 flex items-center justify-between sticky top-14 bg-white/90 backdrop-blur z-40">
        <div class="flex items-center gap-3">
          <button (click)="goBack()" class="text-gray-800 hover:text-blue-600">
            <i class="fa-solid fa-arrow-left"></i>
          </button>
          <h1 class="font-bold text-lg uppercase tracking-wider text-gray-800">Giỏ hàng</h1>
        </div>
        <span class="text-xs font-bold text-gray-500">{{ totalCount }} SP</span>
      </div>

      <!-- Empty State -->
      <div *ngIf="items.length === 0" class="text-center py-20 text-gray-400">
        <i class="fa-solid fa-bag-shopping text-5xl mb-4 text-gray-200"></i>
        <p class="text-sm font-bold uppercase tracking-widest text-gray-500 mb-6">Giỏ hàng trống</p>
        <a routerLink="/catalog" class="inline-block px-8 py-3 bg-black text-white text-xs font-bold uppercase tracking-widest rounded-full hover:bg-gray-800 transition-colors">Mua sắm ngay</a>
      </div>

      <!-- Cart Items -->
      <div *ngIf="items.length > 0" class="p-4 space-y-6">
        <div *ngFor="let item of items" class="flex gap-4 animate-[fadeIn_0.3s_ease-out]">
          <!-- Product Image -->
          <div class="w-24 h-32 bg-gray-100 rounded-xl overflow-hidden shrink-0">
            <img [src]="item.image || 'https://via.placeholder.com/150'" class="w-full h-full object-cover">
          </div>
          
          <!-- Product Details -->
          <div class="flex-1 flex flex-col">
            <div class="flex justify-between items-start gap-2">
              <div>
                <h3 class="text-sm font-bold text-gray-900 uppercase leading-snug line-clamp-2">
                  {{ item.name }}
                </h3>
                <p class="text-xs text-gray-500 mt-1 capitalize">
                  {{ item.color || 'Mặc định' }} <span *ngIf="item.size">/ {{ item.size }}</span>
                </p>
              </div>
              <button (click)="removeItem(item.id)" class="text-gray-400 hover:text-red-500 transition-colors shrink-0">
                <i class="fa-solid fa-trash-can"></i>
              </button>
            </div>
            
            <div class="mt-auto flex justify-between items-end">
              <span class="text-sm font-bold text-blue-600">
                {{ item.price | currency:'VND':'symbol':'1.0-0' }}
              </span>
              
              <!-- Quantity Control -->
              <div class="flex items-center gap-3 border border-gray-200 rounded-full px-2 py-1">
                <button (click)="updateQty(item.id, item.quantity - 1)" class="w-6 h-6 flex items-center justify-center text-gray-500 hover:text-black">
                  <i class="fa-solid fa-minus text-[10px]"></i>
                </button>
                <span class="text-xs font-bold w-4 text-center">{{ item.quantity }}</span>
                <button (click)="updateQty(item.id, item.quantity + 1)" class="w-6 h-6 flex items-center justify-center text-gray-500 hover:text-black">
                  <i class="fa-solid fa-plus text-[10px]"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Summary & Checkout (Fixed Bottom) -->
      <div *ngIf="items.length > 0" class="fixed bottom-[65px] w-full md:w-[480px] bg-white border-t border-gray-100 p-4 pb-safe z-40 shadow-[0_-10px_40px_rgba(0,0,0,0.05)]">
        <div class="flex justify-between items-end mb-4">
          <span class="text-xs font-bold text-gray-500 uppercase tracking-widest">Tạm tính</span>
          <span class="text-lg font-black text-gray-900">{{ totalPrice | currency:'VND':'symbol':'1.0-0' }}</span>
        </div>
        <a routerLink="/checkout" class="w-full flex items-center justify-center h-14 bg-black text-white rounded-2xl font-bold uppercase tracking-widest text-xs hover:bg-gray-800 transition-colors shadow-lg shadow-black/20">
          Tiến hành thanh toán
        </a>
      </div>
    </div>
  `
})
export class CartComponent implements OnInit {
  private cartService = inject(CartService);

  items: CartItem[] = [];
  totalPrice = 0;
  totalCount = 0;

  ngOnInit() {
    this.cartService.cart$.subscribe(items => {
      this.items = items;
      this.totalPrice = this.cartService.getTotalPrice();
      this.totalCount = this.cartService.getTotalCount();
    });
  }

  updateQty(id: string, qty: number) {
    if (qty > 0) {
      this.cartService.updateQuantity(id, qty);
    } else {
      this.removeItem(id);
    }
  }

  removeItem(id: string) {
    if (confirm('Bạn muốn xóa sản phẩm này khỏi giỏ?')) {
      this.cartService.removeFromCart(id);
    }
  }

  goBack() {
    window.history.back();
  }
}
