// fe-react/src/app/(client)/brand/page.tsx
import Link from 'next/link';

export default function Page() {
  return (
    <>


    {/* Header Section */}
    <header className="pt-48 pb-20 border-b border-slate-200/60 text-center fade-in">
        <div className="container mx-auto px-8 max-w-4xl">
            <span className="text-indigo-600 text-[10px] font-black uppercase tracking-[0.4em] mb-6 block">Triết lý của chúng tôi</span>
            <h1 className="font-serif text-5xl md:text-7xl font-black italic mb-10 leading-tight">Tinh hoa của sự tĩnh lặng.</h1>
            <p className="text-slate-500 text-base md:text-lg leading-relaxed font-medium px-4">Tại CLOSET, chúng tôi tin rằng sự sang trọng thực sự không nằm ở những logo hào nhoáng hay những thiết kế rườm rà. Sang trọng là khi bạn cảm nhận được giá trị tuyệt đối trong từng đường kim, sợi chỉ, trên những chất liệu thượng hạng được chế tác hoàn toàn thủ công.</p>
        </div>
    </header>

    <main>
        {/* Section: The Craft (Zig-Zag 1) */}
        <section className="py-24 md:py-36 border-b border-slate-200/50">
            <div className="container mx-auto px-8">
                <div className="flex flex-col md:flex-row items-center gap-16 md:gap-24 reveal-item">
                    <div className="md:w-1/2">
                        <div className="aspect-[4/5] overflow-hidden rounded-2xl bg-slate-100 shadow-xl">
                            <img src="https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1200" className="w-full h-full object-cover" alt="The Craftsmanship" />
                        </div>
                    </div>
                    <div className="md:w-1/2 max-w-lg">
                        <span className="text-slate-400 text-[10px] font-black uppercase tracking-[0.4em] mb-4 block">Nghệ nhân & Kỹ thuật</span>
                        <h2 className="font-serif text-4xl md:text-5xl font-black mb-8 leading-tight"><i className="font-normal italic text-slate-400">The</i> Craft.</h2>
                        <p className="text-slate-600 leading-relaxed mb-6 text-sm">Quá trình tạo ra một chiếc áo khoác của CLOSET đòi hỏi hơn 40 giờ lao động thủ công từ những nghệ nhân có ít nhất 15 năm kinh nghiệm. Mỗi chi tiết nhỏ, từ những khuy cài sừng thật đến các mũi khâu ẩn, đều được thực hiện với độ chính xác tuyệt đối.</p>
                        <p className="text-slate-600 leading-relaxed text-sm">Chúng tôi từ chối sản xuất công nghiệp hàng loạt để giữ gìn cái hồn của nghệ thuật may đo truyền thống, nơi máy móc không thể thay thế bàn tay con người.</p>
                    </div>
                </div>
            </div>
        </section>

        {/* Section: The Materials (Zig-Zag 2) */}
        <section className="py-24 md:py-36 bg-white">
            <div className="container mx-auto px-8">
                <div className="flex flex-col md:flex-row-reverse items-center gap-16 md:gap-24 reveal-item">
                    <div className="md:w-1/2">
                        <div className="aspect-square md:aspect-[4/5] overflow-hidden rounded-2xl bg-slate-100 shadow-xl">
                            <img src="https://images.pexels.com/photos/2220329/pexels-photo-2220329.jpeg?auto=compress&cs=tinysrgb&w=1200" className="w-full h-full object-cover" alt="Premium Materials" />
                        </div>
                    </div>
                    <div className="md:w-1/2 max-w-lg">
                        <span className="text-slate-400 text-[10px] font-black uppercase tracking-[0.4em] mb-4 block">Nguồn gốc nguyên liệu</span>
                        <h2 className="font-serif text-4xl md:text-5xl font-black mb-8 leading-tight"><i className="font-normal italic text-slate-400">Pure</i> Materials.</h2>
                        <p className="text-slate-600 leading-relaxed mb-6 text-sm">Chúng tôi tìm kiếm những nhà cung cấp sợi tốt nhất trên thế giới. Lụa tơ tằm nguyên bản, len Merino siêu mịn từ Australia và Cashmere tinh khiết từ cao nguyên Nội Mông.</p>
                        <p className="text-slate-600 leading-relaxed text-sm">Sự bền vững là ưu tiên hàng đầu. Chúng tôi chỉ hợp tác với các trang trại chăn nuôi nhân đạo và các xưởng nhuộm tuân thủ tiêu chuẩn sinh thái nghiêm ngặt nhất.</p>
                    </div>
                </div>
            </div>
        </section>

        {/* Philosophy Banner */}
        <section className="relative py-40 bg-[#0b0c10] text-white overflow-hidden">
            <div className="absolute inset-0 z-0 opacity-40">
                <img src="https://images.pexels.com/photos/842811/pexels-photo-842811.jpeg?auto=compress&cs=tinysrgb&w=2400" className="w-full h-full object-cover" alt="Creative Director" />
                <div className="absolute inset-0 bg-black/70"></div>
            </div>
            
            <div className="container mx-auto px-8 text-center relative z-10 max-w-4xl reveal-item">
                <i className="fa-solid fa-quote-left text-4xl text-indigo-500/50 mb-8"></i>
                <p className="font-serif text-3xl md:text-5xl font-black italic leading-snug mb-10">
                    "Trang phục không nên làm lu mờ người mặc. Nó sinh ra để là phông nền tĩnh lặng, làm nổi bật khí chất bên trong của bạn."
                </p>
                <div className="w-16 h-[1px] bg-white/30 mx-auto mb-6"></div>
                <h4 className="text-sm font-bold uppercase tracking-[0.2em] mb-1">Alexandre Nguyen</h4>
                <cite className="text-[10px] font-black uppercase tracking-widest text-white/50 block">Giám đốc Sáng tạo</cite>
            </div>
        </section>

    </main>

    
    </>
  );
}

// FE_angular/src/app/pages/brand/brand.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-brand',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="bg-[#f5f5f0] min-h-screen pb-[100px] animate-[fadeIn_0.5s_ease-out]">
      <!-- Hero -->
      <div class="relative w-full h-[70vh] flex items-center justify-center">
        <img src="https://images.pexels.com/photos/991509/pexels-photo-991509.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="absolute inset-0 w-full h-full object-cover">
        <div class="absolute inset-0 bg-black/40"></div>
        <div class="relative z-10 text-center px-4">
          <p class="text-[10px] font-bold text-white uppercase tracking-[0.3em] mb-4">Câu chuyện thương hiệu</p>
          <h1 class="font-serif font-black italic text-5xl text-white mb-6 leading-tight">Quiet Luxury<br>Since 2026</h1>
        </div>
      </div>

      <!-- Philosophy -->
      <div class="py-16 px-6 max-w-lg mx-auto text-center">
        <i class="fa-solid fa-quote-left text-3xl text-gray-300 mb-6"></i>
        <p class="font-serif italic text-2xl text-gray-900 leading-relaxed mb-6">
          Chúng tôi tin rằng sự sang trọng không nằm ở những logo lớn hay thiết kế hào nhoáng, mà nằm ở chất liệu tinh tuyển và sự vừa vặn hoàn hảo.
        </p>
        <p class="text-sm text-gray-500 font-medium uppercase tracking-widest">— Đội ngũ CLOSET</p>
      </div>

      <!-- Detail Sections -->
      <div class="flex flex-col gap-1">
        
        <!-- Section 1 -->
        <div class="bg-white p-8">
          <div class="w-12 h-12 bg-gray-50 rounded-full flex items-center justify-center mb-6">
            <i class="fa-solid fa-leaf text-xl text-gray-600"></i>
          </div>
          <h2 class="font-serif font-bold text-3xl text-gray-900 mb-4">Chất liệu bền vững</h2>
          <p class="text-gray-600 leading-relaxed text-sm">
            100% nguyên liệu của CLOSET được tuyển chọn từ những nhà cung cấp đạt chuẩn sinh thái. Chúng tôi ưu tiên Organic Cotton, Linen, và len Merino không chỉ vì trải nghiệm trên da tuyệt vời mà còn vì trách nhiệm với môi trường.
          </p>
        </div>

        <!-- Section 2 -->
        <div class="bg-white p-8">
          <div class="w-12 h-12 bg-gray-50 rounded-full flex items-center justify-center mb-6">
            <i class="fa-solid fa-scissors text-xl text-gray-600"></i>
          </div>
          <h2 class="font-serif font-bold text-3xl text-gray-900 mb-4">Thiết kế vượt thời gian</h2>
          <p class="text-gray-600 leading-relaxed text-sm">
            Mỗi thiết kế của chúng tôi đều ra đời với mục tiêu: Có thể mặc trong 10 năm tới mà không hề lỗi mốt. Bảng màu trung tính và đường cắt may tối giản chính là ngôn ngữ thời trang mà CLOSET theo đuổi.
          </p>
        </div>

        <!-- Section 3 -->
        <div class="bg-white p-8">
          <div class="w-12 h-12 bg-gray-50 rounded-full flex items-center justify-center mb-6">
            <i class="fa-solid fa-handshake text-xl text-gray-600"></i>
          </div>
          <h2 class="font-serif font-bold text-3xl text-gray-900 mb-4">Mức giá trung thực</h2>
          <p class="text-gray-600 leading-relaxed text-sm">
            Thay vì tốn chi phí cho những chiến dịch quảng cáo rầm rộ hay những mặt bằng đắt đỏ, chúng tôi dồn toàn bộ chi phí vào việc nâng cao chất lượng sản phẩm. Đó là lý do bạn có được chất lượng của những thương hiệu cao cấp với mức giá dễ tiếp cận.
          </p>
        </div>

      </div>

      <!-- CTA -->
      <div class="py-16 px-6 text-center bg-black mt-1">
        <h2 class="font-serif italic font-bold text-3xl text-white mb-6">Trải nghiệm sự khác biệt</h2>
        <a routerLink="/catalog" class="inline-block px-10 py-4 bg-white text-black text-xs font-black uppercase tracking-widest hover:bg-gray-200 transition-colors">
          Khám phá sản phẩm
        </a>
      </div>

    </div>
  `
})
export class BrandComponent {}
