// fe-react/src/app/(client)/post-detail/page.tsx
import Link from 'next/link';

export default function Page() {
  return (
    <>


    <article className="pt-40 pb-20">
        <div className="container mx-auto px-8 max-w-4xl">
            {/* Header */}
            <header className="text-center mb-20">
                <span className="text-[9px] font-black uppercase tracking-[0.4em] text-indigo-600 mb-6 block">Xu hướng</span>
                <h1 className="font-serif text-5xl md:text-7xl font-black italic mb-10 leading-tight">Nghệ thuật phối đồ tối giản cho mùa Thu 2026.</h1>
                <div className="flex items-center justify-center gap-6 text-[10px] font-black uppercase tracking-widest text-slate-400">
                    <span>Thịnh Admin</span>
                    <span className="w-1 h-1 bg-slate-200 rounded-full"></span>
                    <span>15 Tháng 5, 2026</span>
                </div>
            </header>

            {/* Featured Image */}
            <div className="aspect-video bg-slate-100 overflow-hidden mb-20">
                <img src="https://images.unsplash.com/photo-1490481651871-ab68624d5517?auto=format&fit=crop&q=80&w=2000" className="w-full h-full object-cover" alt="" />
            </div>

            {/* Content */}
            <div className="space-y-12 text-slate-600 text-lg leading-relaxed first-letter:text-7xl first-letter:font-serif first-letter:font-black first-letter:mr-4 first-letter:float-left first-letter:text-slate-900">
                <p>Mùa thu không chỉ là sự thay đổi của thời tiết, mà còn là khoảnh khắc để chúng ta làm mới lại tâm hồn và phong cách cá nhân. Tại Closet, chúng tôi luôn tin rằng sự đơn giản chính là đỉnh cao của sự tinh tế. Thay vì chạy theo những xu hướng nhất thời, việc tập trung vào chất liệu và phom dáng sẽ giúp bạn tỏa sáng một cách thầm lặng nhưng đầy uy quyền.</p>

                <h2 className="font-serif text-3xl text-slate-900 font-black italic">1. Sức mạnh của các gam màu trung tính</h2>
                <p>Màu be, xám khói, và xanh navy là những "vũ khí" bí mật của phong cách Quiet Luxury. Việc kết hợp các sắc độ khác nhau của cùng một tông màu sẽ tạo nên một chiều sâu thị giác đầy thú vị mà không cần đến những họa tiết cầu kỳ.</p>
                
                <div className="grid grid-cols-2 gap-8 my-16">
                    <img src="https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800" className="w-full aspect-[3/4] object-cover" alt="" />
                    <img src="https://images.unsplash.com/photo-1539109132314-3477524c859c?w=800" className="w-full aspect-[3/4] object-cover" alt="" />
                </div>

                <h2 className="font-serif text-3xl text-slate-900 font-black italic">2. Chất liệu là linh hồn</h2>
                <p>Một chiếc áo khoác Merino hay một bộ suit lụa tơ tằm không chỉ đẹp ở vẻ ngoài mà còn ở cảm giác chạm vào làn da. Đầu tư vào chất liệu là cách bạn thể hiện sự tôn trọng với chính bản thân mình.</p>

                <blockquote className="border-l-4 border-indigo-600 pl-8 py-4 my-16">
                    <p className="font-serif text-2xl text-slate-800 italic">"Thời trang có thể mua được, nhưng phong cách là thứ bạn phải sở hữu."</p>
                    <cite className="text-[10px] font-black uppercase tracking-widest text-slate-400 mt-4 block">— Nhà thiết kế Closet</cite>
                </blockquote>

                <p>Kết thúc bài viết này, chúng tôi hy vọng bạn sẽ tìm thấy cảm hứng để kiến tạo nên một tủ đồ tối giản nhưng mang đậm dấu ấn cá nhân. Hãy nhớ rằng, sự sang trọng không nằm ở logo, mà nằm ở thần thái và cách bạn lựa chọn những gì tốt nhất cho mình.</p>
            </div>

            {/* Share & Navigation */}
            <footer className="mt-24 pt-10 border-t border-slate-100 flex flex-col md:flex-row justify-between items-center gap-10">
                <div className="flex gap-6">
                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Chia sẻ:</span>
                    <a href="#" className="hover:text-indigo-600 transition-all"><i className="fa-brands fa-facebook-f"></i></a>
                    <a href="#" className="hover:text-indigo-600 transition-all"><i className="fa-brands fa-pinterest-p"></i></a>
                    <a href="#" className="hover:text-indigo-600 transition-all"><i className="fa-brands fa-twitter"></i></a>
                </div>
                <div className="flex gap-12">
                    <a href="#" className="text-[10px] font-black uppercase tracking-widest group">
                        <span className="text-slate-400 block mb-1">Bài trước</span>
                        <span className="group-hover:text-indigo-600 transition-all">Bí quyết chọn vải</span>
                    </a>
                    <a href="#" className="text-[10px] font-black uppercase tracking-widest group text-right">
                        <span className="text-slate-400 block mb-1">Bài tiếp</span>
                        <span className="group-hover:text-indigo-600 transition-all">Paris Lookbook</span>
                    </a>
                </div>
            </footer>
        </div>
    </article>

    
    </>
  );
}

// FE_angular/src/app/pages/post-detail/post-detail.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-post-detail',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="bg-white min-h-screen pb-[100px] animate-[fadeIn_0.3s_ease-out]">
      <!-- Sticky Header for Reading -->
      <div class="sticky top-0 z-40 bg-white/90 backdrop-blur-md border-b border-gray-100 p-4 flex items-center justify-between">
        <button (click)="goBack()" class="w-10 h-10 flex items-center justify-center text-gray-500 hover:text-black transition-colors rounded-full bg-gray-50">
          <i class="fa-solid fa-arrow-left"></i>
        </button>
        <div class="flex gap-2">
          <button class="w-10 h-10 flex items-center justify-center text-gray-500 hover:text-blue-600 transition-colors rounded-full bg-gray-50">
            <i class="fa-regular fa-bookmark"></i>
          </button>
          <button class="w-10 h-10 flex items-center justify-center text-gray-500 hover:text-blue-600 transition-colors rounded-full bg-gray-50">
            <i class="fa-solid fa-share-nodes"></i>
          </button>
        </div>
      </div>

      <!-- Hero Image -->
      <div class="w-full aspect-[4/3] relative">
        <img src="https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800" class="w-full h-full object-cover">
        <div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
        <div class="absolute bottom-6 left-6 right-6 text-white">
          <div class="mb-3 flex gap-2">
            <span class="bg-white/20 backdrop-blur-sm px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest text-white">
              Phối đồ
            </span>
          </div>
          <h1 class="text-2xl font-serif font-black italic leading-tight mb-3">
            Làm thế nào để mặc phong cách Quiet Luxury đúng chuẩn?
          </h1>
          <div class="flex items-center gap-3 text-xs text-gray-300 font-medium">
            <span><i class="fa-regular fa-clock mr-1"></i> 14 Tháng 7, 2026</span>
            <span class="w-1 h-1 bg-gray-400 rounded-full"></span>
            <span>Tác giả: CLOSET Team</span>
          </div>
        </div>
      </div>

      <!-- Post Content -->
      <div class="p-6">
        <div class="prose prose-sm md:prose-base prose-slate max-w-none">
          <p class="text-lg font-medium text-gray-600 leading-relaxed mb-6 italic">
            "Sang trọng tĩnh lặng" (Quiet Luxury) không phải là trào lưu nhất thời, mà là một lối sống. Bí quyết nằm ở chất liệu và sự tối giản.
          </p>

          <p class="mb-4 text-gray-800 leading-loose">
            Bạn có bao giờ tự hỏi làm sao một người có thể trông cực kỳ đắt tiền mà không hề có bất kỳ logo hàng hiệu nào trên người? Đó chính là cốt lõi của Quiet Luxury.
          </p>

          <h3 class="text-xl font-bold mt-8 mb-4">1. Tập trung vào chất liệu</h3>
          <p class="mb-4 text-gray-800 leading-loose">
            Cashmere, lụa tơ tằm, len merino hay cotton Ai Cập. Những chất liệu này tự thân nó đã toát lên vẻ đẹp đắt giá qua độ rủ, độ bóng nhẹ và cảm giác tuyệt vời khi chạm vào da.
          </p>

          <img src="https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=800" class="w-full rounded-2xl my-6">

          <h3 class="text-xl font-bold mt-8 mb-4">2. Bảng màu trung tính</h3>
          <p class="mb-4 text-gray-800 leading-loose">
            Beige, navy, xám, trắng, và đen. Hãy chọn những tông màu không bao giờ lỗi mốt. Phối đồ theo kiểu ton-sur-ton (monochrome) cũng là một mẹo rất hay để hack dáng và trông thanh lịch hơn.
          </p>

          <div class="bg-gray-50 p-6 rounded-2xl border-l-4 border-black my-8">
            <p class="font-serif italic text-lg text-gray-900 leading-relaxed mb-0">
              "Sự sang trọng thực sự là khi bạn không cần phải hét lên để người khác biết bạn là ai."
            </p>
          </div>

          <h3 class="text-xl font-bold mt-8 mb-4">3. Vừa vặn hoàn hảo (Tailoring)</h3>
          <p class="mb-4 text-gray-800 leading-loose">
            Một chiếc áo khoác rẻ tiền nhưng được may đo vừa vặn ôm khít cơ thể sẽ luôn trông đẹp hơn một chiếc áo khoác hàng hiệu nhưng sai size. Hãy tìm cho mình một người thợ may giỏi.
          </p>
        </div>
      </div>

      <!-- Related Products -->
      <div class="px-6 py-8 bg-gray-50 border-t border-gray-100">
        <h3 class="font-black text-lg uppercase tracking-widest mb-6 text-center">Sản phẩm gợi ý</h3>
        <!-- Horizontal Scroll of Products -->
        <div class="flex gap-4 overflow-x-auto no-scrollbar pb-4">
          
          <a routerLink="/catalog" class="w-[140px] shrink-0 group">
            <div class="bg-white rounded-xl overflow-hidden aspect-[3/4] mb-3 relative">
              <img src="https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400" class="w-full h-full object-cover">
            </div>
            <h4 class="text-xs font-bold text-gray-900 line-clamp-1 mb-1">Áo Vest Nam Cổ Điển</h4>
            <p class="text-[10px] text-gray-500 font-bold">1,250,000đ</p>
          </a>

          <a routerLink="/catalog" class="w-[140px] shrink-0 group">
            <div class="bg-white rounded-xl overflow-hidden aspect-[3/4] mb-3 relative">
              <img src="https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg?auto=compress&cs=tinysrgb&w=400" class="w-full h-full object-cover">
            </div>
            <h4 class="text-xs font-bold text-gray-900 line-clamp-1 mb-1">Quần Tây Slimfit</h4>
            <p class="text-[10px] text-gray-500 font-bold">650,000đ</p>
          </a>

        </div>
      </div>
    </div>
  `
})
export class PostDetailComponent {
  goBack() {
    window.history.back();
  }
}
