// fe-react/src/components/client/Footer/index.tsx
import Link from "next/link";

export default function Footer() {
  return (
    <footer className="bg-white dark:bg-[#171717] border-t border-slate-200/80 dark:border-[#D4AF37]/20 pt-16 pb-8 transition-colors duration-300">
      <div className="container mx-auto px-4 md:px-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-12">
          <div className="md:col-span-1">
            <h2 className="font-serif text-2xl font-black tracking-tighter text-slate-900 dark:text-slate-100 mb-1">
              CLOSET.
            </h2>
            <p className="text-[10px] font-bold text-indigo-600 dark:text-[#D4AF37] uppercase tracking-[0.25em] mb-4">
              THE ART OF DRESSING
            </p>
            <p className="text-slate-500 dark:text-slate-400 text-sm mb-6 leading-relaxed">
              Trải nghiệm mua sắm thời trang tối giản, tinh tế và sang trọng. Tự
              tin thể hiện phong cách độc bản của chính bạn.
            </p>
            <div className="flex gap-4">
              <Link
                href="#"
                className="w-8 h-8 rounded-full bg-slate-100 dark:bg-[#232223] border border-slate-200 dark:border-slate-800 flex items-center justify-center text-slate-600 dark:text-slate-300 hover:bg-indigo-600 dark:hover:bg-[#D4AF37] hover:text-white dark:hover:text-black transition-colors"
              >
                <i className="fa-brands fa-facebook-f text-sm"></i>
              </Link>
              <Link
                href="#"
                className="w-8 h-8 rounded-full bg-slate-100 dark:bg-[#232223] border border-slate-200 dark:border-slate-800 flex items-center justify-center text-slate-600 dark:text-slate-300 hover:bg-indigo-600 dark:hover:bg-[#D4AF37] hover:text-white dark:hover:text-black transition-colors"
              >
                <i className="fa-brands fa-instagram text-sm"></i>
              </Link>
            </div>
          </div>

          <div>
            <h3 className="font-bold text-slate-900 dark:text-slate-100 mb-4 uppercase tracking-wider text-sm">
              Cửa hàng
            </h3>
            <ul className="flex flex-col gap-3 text-sm text-slate-500 dark:text-slate-400">
              <li>
                <Link
                  href="/shop"
                  className="hover:text-indigo-600 dark:hover:text-[#EBC563] transition-colors"
                >
                  Tất cả sản phẩm
                </Link>
              </li>
              <li>
                <Link
                  href="/shop"
                  className="hover:text-indigo-600 dark:hover:text-[#EBC563] transition-colors"
                >
                  Hàng mới về
                </Link>
              </li>
              <li>
                <Link
                  href="/shop?discount=true"
                  className="hover:text-indigo-600 dark:hover:text-[#D4AF37] transition-colors text-red-500 dark:text-amber-400 font-bold"
                >
                  Giảm giá
                </Link>
              </li>
            </ul>
          </div>

          <div>
            <h3 className="font-bold text-slate-900 dark:text-slate-100 mb-4 uppercase tracking-wider text-sm">
              Hỗ trợ
            </h3>
            <ul className="flex flex-col gap-3 text-sm text-slate-500 dark:text-slate-400">
              <li>
                <Link
                  href="#"
                  className="hover:text-indigo-600 dark:hover:text-[#EBC563] transition-colors"
                >
                  Hướng dẫn mua hàng
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="hover:text-indigo-600 dark:hover:text-[#EBC563] transition-colors"
                >
                  Chính sách đổi trả
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="hover:text-indigo-600 dark:hover:text-[#EBC563] transition-colors"
                >
                  Chính sách bảo mật
                </Link>
              </li>
            </ul>
          </div>

          <div>
            <h3 className="font-bold text-slate-900 dark:text-slate-100 mb-4 uppercase tracking-wider text-sm">
              Nhận bản tin
            </h3>
            <p className="text-sm text-slate-500 dark:text-slate-400 mb-4">
              Đăng ký để nhận ưu đãi đặc quyền và bộ sưu tập mới nhất.
            </p>
            <form className="flex">
              <input
                type="email"
                placeholder="Email của bạn"
                className="flex-1 bg-slate-100 dark:bg-[#232223] text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-700 px-4 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-indigo-500 dark:focus:ring-[#D4AF37] rounded-l-xl"
              />
              <button
                type="button"
                className="bg-indigo-600 dark:bg-[#D4AF37] text-white dark:text-black px-4 py-2 text-sm font-bold hover:bg-indigo-700 dark:hover:bg-[#EBC563] transition-colors rounded-r-xl"
              >
                Đăng ký
              </button>
            </form>
          </div>
        </div>

        <div className="border-t border-slate-200/80 dark:border-slate-800 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-slate-400 dark:text-slate-500 text-xs">
            &copy; 2026 CLOSET. Tất cả quyền được bảo lưu.
          </p>
        </div>
      </div>
    </footer>
  );
}

// FE_angular/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <footer class="bg-gray-950 text-gray-400 pt-10 pb-24 px-5 border-t border-gray-800 relative overflow-hidden">
      <!-- Ambient light glow -->
      <div class="absolute top-0 left-1/4 w-72 h-72 bg-blue-600/10 rounded-full blur-3xl pointer-events-none"></div>

      <div class="max-w-md mx-auto relative z-10 space-y-8">
        <!-- Brand Info -->
        <div>
          <h3 class="font-serif-brand text-3xl font-black tracking-tighter mb-3 flex items-center">
            <span class="bg-gradient-to-r from-[#D4AF37] via-[#EBC563] to-[#B38B1B] bg-clip-text text-transparent">CLOSET</span>
            <span class="text-amber-500 font-sans text-lg font-black -ml-0.5">.</span>
          </h3>
          <p class="text-xs text-gray-400 leading-relaxed mb-5">
            Đỉnh cao của nghệ thuật tối giản và thời trang thượng hạng. Định hình phong cách sang trọng thầm lặng.
          </p>

          <!-- Social Icons -->
          <div class="flex items-center gap-3">
            <a href="#" class="w-9 h-9 rounded-full border border-gray-800 flex items-center justify-center text-gray-400 hover:text-white hover:border-white transition-colors">
              <i class="fa-brands fa-instagram text-xs"></i>
            </a>
            <a href="#" class="w-9 h-9 rounded-full border border-gray-800 flex items-center justify-center text-gray-400 hover:text-white hover:border-white transition-colors">
              <i class="fa-brands fa-facebook-f text-xs"></i>
            </a>
            <a href="#" class="w-9 h-9 rounded-full border border-gray-800 flex items-center justify-center text-gray-400 hover:text-white hover:border-white transition-colors">
              <i class="fa-brands fa-pinterest-p text-xs"></i>
            </a>
            <a href="#" class="w-9 h-9 rounded-full border border-gray-800 flex items-center justify-center text-gray-400 hover:text-white hover:border-white transition-colors">
              <i class="fa-brands fa-tiktok text-xs"></i>
            </a>
          </div>
        </div>

        <!-- Newsletter Signup -->
        <div class="bg-gray-900/80 p-4 rounded-2xl border border-gray-800/80">
          <h4 class="text-xs font-black uppercase tracking-widest text-white mb-2">Đăng ký nhận bản tin</h4>
          <p class="text-[11px] text-gray-400 leading-relaxed mb-3">Nhận thông tin bộ sưu tập mới và ưu đãi đặc quyền.</p>
          <div class="flex gap-2">
            <input type="email" placeholder="Email của bạn..." class="flex-1 bg-black border border-gray-800 px-3.5 py-2.5 rounded-xl text-xs text-white outline-none focus:border-white transition-all placeholder:text-gray-600">
            <button type="button" class="px-4 py-2.5 bg-white text-black font-black text-[10px] uppercase tracking-widest rounded-xl hover:bg-gray-200 transition-colors shrink-0">
              Đăng ký
            </button>
          </div>
        </div>

        <!-- Links Section -->
        <div class="grid grid-cols-2 gap-6 pt-2 border-t border-gray-900 text-xs">
          <div>
            <h4 class="text-[10px] font-black uppercase tracking-widest text-white mb-3">Bộ sưu tập</h4>
            <ul class="space-y-2 text-gray-400">
              <li><a routerLink="/catalog" class="hover:text-white transition-colors">Classic Suit</a></li>
              <li><a routerLink="/catalog" class="hover:text-white transition-colors">Heritage Overcoat</a></li>
              <li><a routerLink="/catalog" class="hover:text-white transition-colors">Merino Knitwear</a></li>
              <li><a routerLink="/catalog" class="hover:text-white transition-colors">Evening Dress</a></li>
            </ul>
          </div>

          <div>
            <h4 class="text-[10px] font-black uppercase tracking-widest text-white mb-3">Khám phá</h4>
            <ul class="space-y-2 text-gray-400">
              <li><a routerLink="/brand" class="hover:text-white transition-colors">Về CLOSET</a></li>
              <li><a routerLink="/blog" class="hover:text-white transition-colors">Tạp chí Journal</a></li>
              <li><a routerLink="/lookbook" class="hover:text-white transition-colors">Lookbook 2026</a></li>
              <li><a routerLink="/catalog" class="hover:text-white transition-colors">Hệ thống cửa hàng</a></li>
            </ul>
          </div>
        </div>

        <!-- Store Info & Support -->
        <div class="bg-gray-900/40 p-4 rounded-2xl border border-gray-900 text-xs space-y-3">
          <div>
            <strong class="text-white block text-[11px] font-bold uppercase tracking-wider mb-1">
              <i class="fa-solid fa-location-dot text-red-500 mr-1.5"></i> Flagship Store
            </strong>
            <p class="text-gray-400 text-[11px] leading-relaxed">123 Đường Đồng Khởi, Bến Nghé, Quận 1, TP. HCM</p>
          </div>

          <div class="pt-2 border-t border-gray-800/50">
            <strong class="text-white block text-[11px] font-bold uppercase tracking-wider mb-1">
              <i class="fa-solid fa-phone text-emerald-500 mr-1.5"></i> Hotline hỗ trợ
            </strong>
            <p class="text-gray-400 text-[11px]">1900 123 456 (9:00 - 22:00)</p>
          </div>
        </div>

        <!-- Bottom Copyright & Payments -->
        <div class="pt-6 border-t border-gray-900 text-[10px] text-gray-500 flex flex-col items-center gap-3 text-center">
          <div class="flex items-center gap-4 text-lg text-gray-600">
            <i class="fa-brands fa-cc-visa hover:text-white transition-colors"></i>
            <i class="fa-brands fa-cc-mastercard hover:text-white transition-colors"></i>
            <i class="fa-brands fa-cc-apple-pay hover:text-white transition-colors"></i>
            <i class="fa-solid fa-money-bill-transfer hover:text-white transition-colors"></i>
          </div>
          <p>© 2026 CLOSET Store. All Rights Reserved.</p>
        </div>
      </div>
    </footer>
  `
})
export class FooterComponent {}
